<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Shared\MagicMouseWindows.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <AssemblyName>MagicMouseSettings</AssemblyName>
    <RootNamespace>MagicMouseWindows.SettingsApp</RootNamespace>
  </PropertyGroup>

</Project>
