#include <ntddk.h>
#include <wdf.h>
#include <vhf.h>

#include "VhfWheelTestProtocol.h"

DRIVER_INITIALIZE DriverEntry;
EVT_WDF_DRIVER_DEVICE_ADD VhfWheelTestEvtDeviceAdd;
EVT_WDF_DEVICE_PREPARE_HARDWARE VhfWheelTestEvtDevicePrepareHardware;
EVT_WDF_OBJECT_CONTEXT_CLEANUP VhfWheelTestEvtDeviceCleanup;
EVT_WDF_IO_QUEUE_IO_DEVICE_CONTROL VhfWheelTestEvtIoDeviceControl;

static const GUID GUID_DEVINTERFACE_VHF_WHEEL_TEST = {
    0xb44e70a5,
    0xf238,
    0x49ba,
    {0x94, 0x0c, 0x09, 0x34, 0x86, 0x0e, 0x91, 0xe1}};

typedef struct _DEVICE_CONTEXT {
    VHFHANDLE VhfHandle;
} DEVICE_CONTEXT, *PDEVICE_CONTEXT;

WDF_DECLARE_CONTEXT_TYPE_WITH_NAME(DEVICE_CONTEXT, DeviceGetContext);
C_ASSERT(sizeof(VHF_WHEEL_TEST_REQUEST) == 20);

#pragma pack(push, 1)
typedef struct _VHF_WHEEL_INPUT_REPORT {
    UCHAR ReportId;
    UCHAR Buttons;
    CHAR X;
    CHAR Y;
    CHAR Vertical;
    CHAR Horizontal;
} VHF_WHEEL_INPUT_REPORT;
#pragma pack(pop)

static const UCHAR VhfWheelTestReportDescriptor[] = {
    0x05, 0x01,       // Usage Page (Generic Desktop)
    0x09, 0x02,       // Usage (Mouse)
    0xA1, 0x01,       // Collection (Application)
    0x85, 0x01,       //   Report ID (1)
    0x09, 0x01,       //   Usage (Pointer)
    0xA1, 0x00,       //   Collection (Physical)
    0x05, 0x09,       //     Usage Page (Button)
    0x19, 0x01,       //     Usage Minimum (1)
    0x29, 0x03,       //     Usage Maximum (3)
    0x15, 0x00,       //     Logical Minimum (0)
    0x25, 0x01,       //     Logical Maximum (1)
    0x75, 0x01,       //     Report Size (1)
    0x95, 0x03,       //     Report Count (3)
    0x81, 0x02,       //     Input (Data, Variable, Absolute)
    0x95, 0x05,       //     Report Count (5)
    0x81, 0x03,       //     Input (Constant, Variable, Absolute)
    0x05, 0x01,       //     Usage Page (Generic Desktop)
    0x15, 0x81,       //     Logical Minimum (-127)
    0x25, 0x7F,       //     Logical Maximum (127)
    0x75, 0x08,       //     Report Size (8)
    0x95, 0x02,       //     Report Count (2)
    0x09, 0x30,       //     Usage (X)
    0x09, 0x31,       //     Usage (Y)
    0x81, 0x06,       //     Input (Data, Variable, Relative)
    0x95, 0x01,       //     Report Count (1)
    0x09, 0x38,       //     Usage (Wheel)
    0x81, 0x06,       //     Input (Data, Variable, Relative)
    0x05, 0x0C,       //     Usage Page (Consumer)
    0x0A, 0x38, 0x02, //     Usage (AC Pan)
    0x81, 0x06,       //     Input (Data, Variable, Relative)
    0xC0,             //   End Collection
    0xC0              // End Collection
};

NTSTATUS
DriverEntry(
    _In_ PDRIVER_OBJECT DriverObject,
    _In_ PUNICODE_STRING RegistryPath
    )
{
    WDF_DRIVER_CONFIG config;

    WDF_DRIVER_CONFIG_INIT(&config, VhfWheelTestEvtDeviceAdd);
    return WdfDriverCreate(
        DriverObject,
        RegistryPath,
        WDF_NO_OBJECT_ATTRIBUTES,
        &config,
        WDF_NO_HANDLE);
}

NTSTATUS
VhfWheelTestEvtDeviceAdd(
    _In_ WDFDRIVER Driver,
    _Inout_ PWDFDEVICE_INIT DeviceInit
    )
{
    WDF_OBJECT_ATTRIBUTES attributes;
    WDF_IO_QUEUE_CONFIG queueConfig;
    WDFDEVICE device;
    PDEVICE_CONTEXT context;
    NTSTATUS status;
    DECLARE_CONST_UNICODE_STRING(
        deviceSddl,
        L"D:P(A;;GA;;;SY)(A;;GA;;;BA)");

    UNREFERENCED_PARAMETER(Driver);

    WdfDeviceInitSetDeviceType(DeviceInit, FILE_DEVICE_UNKNOWN);
    WdfDeviceInitSetCharacteristics(
        DeviceInit,
        FILE_DEVICE_SECURE_OPEN | FILE_AUTOGENERATED_DEVICE_NAME,
        FALSE);

    status = WdfDeviceInitAssignSDDLString(DeviceInit, &deviceSddl);
    if (!NT_SUCCESS(status)) {
        return status;
    }

    {
        WDF_PNPPOWER_EVENT_CALLBACKS pnpCallbacks;
        WDF_PNPPOWER_EVENT_CALLBACKS_INIT(&pnpCallbacks);
        pnpCallbacks.EvtDevicePrepareHardware = VhfWheelTestEvtDevicePrepareHardware;
        WdfDeviceInitSetPnpPowerEventCallbacks(DeviceInit, &pnpCallbacks);
    }

    WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&attributes, DEVICE_CONTEXT);
    attributes.EvtCleanupCallback = VhfWheelTestEvtDeviceCleanup;
    status = WdfDeviceCreate(&DeviceInit, &attributes, &device);
    if (!NT_SUCCESS(status)) {
        return status;
    }

    context = DeviceGetContext(device);
    context->VhfHandle = NULL;

    status = WdfDeviceCreateDeviceInterface(
        device,
        &GUID_DEVINTERFACE_VHF_WHEEL_TEST,
        NULL);
    if (!NT_SUCCESS(status)) {
        return status;
    }

    WDF_IO_QUEUE_CONFIG_INIT_DEFAULT_QUEUE(
        &queueConfig,
        WdfIoQueueDispatchSequential);
    queueConfig.EvtIoDeviceControl = VhfWheelTestEvtIoDeviceControl;

    return WdfIoQueueCreate(
        device,
        &queueConfig,
        WDF_NO_OBJECT_ATTRIBUTES,
        WDF_NO_HANDLE);
}

NTSTATUS
VhfWheelTestEvtDevicePrepareHardware(
    _In_ WDFDEVICE Device,
    _In_ WDFCMRESLIST ResourcesRaw,
    _In_ WDFCMRESLIST ResourcesTranslated
    )
{
    PDEVICE_CONTEXT context = DeviceGetContext(Device);
    VHF_CONFIG vhfConfig;
    NTSTATUS status;

    UNREFERENCED_PARAMETER(ResourcesRaw);
    UNREFERENCED_PARAMETER(ResourcesTranslated);

    if (context->VhfHandle != NULL) {
        return STATUS_SUCCESS;
    }

    VHF_CONFIG_INIT(
        &vhfConfig,
        WdfDeviceWdmGetDeviceObject(Device),
        sizeof(VhfWheelTestReportDescriptor),
        (PUCHAR)VhfWheelTestReportDescriptor);
    vhfConfig.VendorID = 0x1209;
    vhfConfig.ProductID = 0x0001;
    vhfConfig.VersionNumber = 0x0001;

    status = VhfCreate(&vhfConfig, &context->VhfHandle);
    if (!NT_SUCCESS(status)) {
        context->VhfHandle = NULL;
        return status;
    }

    status = VhfStart(context->VhfHandle);
    if (!NT_SUCCESS(status)) {
        VhfDelete(context->VhfHandle, TRUE);
        context->VhfHandle = NULL;
    }

    return status;
}

VOID
VhfWheelTestEvtDeviceCleanup(
    _In_ WDFOBJECT Object
    )
{
    WDFDEVICE device = (WDFDEVICE)Object;
    PDEVICE_CONTEXT context = DeviceGetContext(device);

    if (context->VhfHandle != NULL) {
        VhfDelete(context->VhfHandle, TRUE);
        context->VhfHandle = NULL;
    }

}

VOID
VhfWheelTestEvtIoDeviceControl(
    _In_ WDFQUEUE Queue,
    _In_ WDFREQUEST Request,
    _In_ size_t OutputBufferLength,
    _In_ size_t InputBufferLength,
    _In_ ULONG IoControlCode
    )
{
    WDFDEVICE device = WdfIoQueueGetDevice(Queue);
    PDEVICE_CONTEXT context = DeviceGetContext(device);
    PVHF_WHEEL_TEST_REQUEST input;
    VHF_WHEEL_INPUT_REPORT report;
    HID_XFER_PACKET packet;
    NTSTATUS status;

    UNREFERENCED_PARAMETER(OutputBufferLength);

    if (IoControlCode != IOCTL_VHF_WHEEL_TEST_INJECT) {
        WdfRequestComplete(Request, STATUS_INVALID_DEVICE_REQUEST);
        return;
    }

    if (InputBufferLength != sizeof(VHF_WHEEL_TEST_REQUEST)) {
        WdfRequestComplete(Request, STATUS_INFO_LENGTH_MISMATCH);
        return;
    }

    status = WdfRequestRetrieveInputBuffer(
        Request,
        sizeof(VHF_WHEEL_TEST_REQUEST),
        (PVOID*)&input,
        NULL);
    if (!NT_SUCCESS(status)) {
        WdfRequestComplete(Request, status);
        return;
    }

    if (input->Size != sizeof(VHF_WHEEL_TEST_REQUEST) ||
        input->Version != VHF_WHEEL_TEST_PROTOCOL_VERSION ||
        input->Reserved != 0 ||
        input->Vertical < VHF_WHEEL_TEST_DELTA_MIN ||
        input->Vertical > VHF_WHEEL_TEST_DELTA_MAX ||
        input->Horizontal < VHF_WHEEL_TEST_DELTA_MIN ||
        input->Horizontal > VHF_WHEEL_TEST_DELTA_MAX ||
        (input->Vertical == 0 && input->Horizontal == 0)) {
        WdfRequestComplete(Request, STATUS_INVALID_PARAMETER);
        return;
    }

    if (context->VhfHandle == NULL) {
        WdfRequestComplete(Request, STATUS_DEVICE_NOT_READY);
        return;
    }

    report.ReportId = 1;
    report.Buttons = 0;
    report.X = 0;
    report.Y = 0;
    report.Vertical = (CHAR)input->Vertical;
    report.Horizontal = (CHAR)input->Horizontal;

    RtlZeroMemory(&packet, sizeof(packet));
    packet.reportBuffer = (PUCHAR)&report;
    packet.reportBufferLen = sizeof(report);
    packet.reportId = report.ReportId;

    status = VhfReadReportSubmit(context->VhfHandle, &packet);
    WdfRequestComplete(Request, status);
}
