#pragma once

#define VHF_WHEEL_TEST_PROTOCOL_VERSION 1u
#define VHF_WHEEL_TEST_DELTA_MIN (-127)
#define VHF_WHEEL_TEST_DELTA_MAX 127

#define IOCTL_VHF_WHEEL_TEST_INJECT \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_WRITE_ACCESS)

typedef struct _VHF_WHEEL_TEST_REQUEST {
    ULONG Size;
    ULONG Version;
    LONG Vertical;
    LONG Horizontal;
    ULONG Reserved;
} VHF_WHEEL_TEST_REQUEST, *PVHF_WHEEL_TEST_REQUEST;
